---
homedir: .
device: auto
network: ???
label: ???
seed: 0
name_tag: null
runid: 0
num_workers: 0  # 0 uses all available threads
out_dir: results
hp_tune: false
log_level: INFO
wandb:
  use: false
  entity: RemyLiu
  project: OBNB-dev
metric:
  options:
    - APOP
    - AP
    - AUROC
  best: APOP
  obj: max
trainer:
  accelerator: auto
  devices: 1
  inference_only: false  # turn on for LabelPropagation
  max_epochs: 50_000
  eval_interval: 20
  early_stopping_patience: 1000
  gradient_clip_val: 0.02  # set to null to disable
  fast_dev_run: false
  watch_grad_norm: true
model:
  hid_dim: 128
  mp_type: GCNConv
  mp_layers: 3
  mp_kwargs: null
  residual_type: skipsumlnorm
  dropout: 0.5
  norm_type: BatchNorm
  norm_kwargs: null
  act: relu
  act_first: false
  pred_head_layers: 1
  skip_pred_act: false
  post_prop:
    enable: false
    num_layers: 10
    alpha: 0.9  # the "not restart" (the converse of teleporting) probability
    norm: left
    dropout: 0.0
    cached: true
  post_cands:
    enable: false
    num_correction_layers: 100
    num_smoothing_layers: 100
    correction_alpha: 1.0
    smoothing_alpha: 0.8
    correction_norm: sym
    smoothing_norm: left
    autoscale: false
    scale: 1.0
    cached: true
node_encoders: OneHotLogDeg
use_edge_feature: true
optim:
  lr: 0.01
  weight_decay: 1e-6
  optimizer: AdamW
  optimizer_kwargs: null
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: ${metric.obj}
    patience: 100
    min_lr: 1e-5
    factor: 0.5
node_encoder_params:
  OneHotLogDeg:
    raw_dim: 32
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  Constant:
    raw_dim: 1
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  RandomNormal:
    raw_dim: 32
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  Orbital:
    enc_dim: 128
    graphlet_size: 3
    raw_bn: true
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  SVD:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  LapEigMap:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  RandomWalkDiag:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.0
    dropout: 0.2
    layers: 1
  RandProjGaussian:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.2
    dropout: 0.2
    layers: 1
  RandProjSparse:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.2
    dropout: 0.2
    layers: 1
  LINE1:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  LINE2:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  Node2vec:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  Walklets:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  Adj:
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  AdjEmbBag:
    raw_dim: 128
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.2
    dropout: 0.2
    layers: 0
  Embedding:
    raw_dim: 128
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.2
    dropout: 0.2
    layers: 0
  LabelReuse:  # turn off dropout and remove enc for LabelPropagation
    raw_bn: true
    enc_dim: 128
    raw_dropout: 0.5
    dropout: 0.2
    layers: 1
  Composed:
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.0
    dropout: 0.2
    layers: 2
