---
homedir: .
device: auto
network: ???
label: ???
seed: 0
name_tag: null
runid: 0
num_workers: 0  # 0 uses all available threads
out_dir: results
hp_tune: false
log_level: INFO
wandb:
  use: false
  entity: RemyLiu
  project: OBNB-dev
metric:
  options:
    - APOP
    - AP
    - AUROC
  best: APOP
  obj: max
trainer:
  max_epochs: 50_000
  eval_interval: 50
  early_stopping_patience: 2000
  gradient_clip_val: 0.02  # set to null to disable
  fast_dev_run: false
  watch_grad_norm: true
node_encoders: OneHotLogDeg
model:
  use_edge_feature: false
  hid_dim: 128
  mp_type: GATv2Conv
  mp_layers: 3
  mp_kwargs: null
  residual_type: skipsum
  dropout: 0.5
  norm_type: BatchNorm
  norm_kwargs: null
  act: relu
  act_first: false
  pred_head_layers: 1
optim:
  lr: 0.01
  weight_decay: 1e-6
  optimizer: AdamW
  optimizer_kwargs: null
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: ${metric.obj}
    patience: 100
    min_lr: 1e-5
    factor: 0.5
node_encoder_params:
  OneHotLogDeg:
    raw_dim: 32
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  Constant:
    raw_dim: 1
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.5
    layers: 1
  RandomNormal:
    raw_dim: 32
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  Orbital:
    enc_dim: 128
    graphlet_size: 3
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  SVD:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  LapEigMap:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  RandomWalkDiag:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  RandProjGaussian:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  RandProjSparse:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  EmbLINE1:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  EmbLINE2:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  EmbNode2vec:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  EmbWalklets:
    raw_dim: 128
    enc_dim: 128
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  LabelReuse:
    raw_bn: true
    raw_dropout: 0.5
    layers: 1
  Composed:
    enc_dim: 128
    raw_bn: false
    raw_dropout: 0.5
    layers: 2
