---
homedir: .
device: auto
network: ???
label: ???
model: ???
name_tag: null
runid: 0
num_workers: 0  # 0 uses all available threads
out_dir: results
hp_tune: false
log_level: INFO
metric_best: log2pr
gnn_params:
  lr: 0.001
  hid_dim: 128
  num_layers: 5
  epochs: 20000
  eval_steps: 100
  node_feat_dim: 32
n2v_params:
  hid_dim: 128
  walk_length: 80
  window_size: 10
  num_walks: 10
lp_params:
  beta: 0.85
optim_params:
  GAT:
    lr: 0.001
    hid_dim: 128
    num_layers: 5
    addopts:
      v2: true
      heads: 8
  GCN:
    lr: 0.001
    hid_dim: 128
    num_layers: 5
  GIN:
    lr: 0.001
    hid_dim: 128
    num_layers: 5
  GraphSAGE:
    lr: 0.001
    hid_dim: 128
    num_layers: 5
    addopts:
      aggr: add
      normalize: true
  LabelProp:
    beta: 0.9
  N2V-LogReg:
    hid_dim: 128
    walk_length: 160
    window_size: 12
  N2V-SVM:
    hid_dim: 128
    walk_length: 160
    window_size: 12
