---
data_version: nledata-v0.1.0-dev6
paths:
  homedir: .
  dataset_dir: ${paths.homedir}/datasets
  gene_list_path: ${paths.homedir}/genes.txt
labels:
  - GOBP
  - DisGeNET
  - DISEASES
networks:
  - STRING
  - BioGRID
  - HumanNet  # same as HumanNet-XC
  - ConsensusPathDB
  - BioPlex
  - ComPPIHumanInt
  - FunCoup
  - HIPPIE
  - HuRI
  - HuMAP
  - OmniPath
  - PCNet
  - ProteomeHD
  - SIGNOR
