---
data_version: obnbdata-0.1.0
paths:
  homedir: .
  runtime_dir: ${paths.homedir}/runtime
  dataset_dir: ${paths.homedir}/datasets
  gene_list_path: ${paths.homedir}/genes.txt
labels:
  - GOBP
  - DisGeNET
  - DISEASES
networks:
  - STRING
  - BioGRID
  - HumanNet  # same as HumanNet-XC
  - ConsensusPathDB
  - BioPlex
  - ComPPIHumanInt
  - FunCoup
  - HIPPIE
  - HuRI
  - HuMAP
  - OmniPath
  - PCNet
  - ProteomeHD
  - SIGNOR
hydra:
  run:
    dir: ${paths.runtime_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
